# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-14 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mande', '0037_auto_20170811_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationMarkingPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128, verbose_name='Description')),
                ('test_date', models.DateField(verbose_name='Test Date')),
                ('marking_period_start', models.DateField(verbose_name='Marking Period Start')),
                ('marking_period_end', models.DateField(verbose_name='Marking Period End')),
            ],
        ),
    ]
