# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-19 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mande', '0040_auto_20171011_1004'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exitsurvey',
            unique_together=set([('student_id', 'exit_date')]),
        ),
    ]
