#set minimum permissions for access of each view (maybe more required for write access!)
perms_required={
    'student_list':{
        'mande.view_intakesurvey',
        'mande.view_intakeinternal',
        'mande.view_exitsurvey'
    },
    'student_detail':{
        'mande.view_intakesurvey',
        'mande.view_exitsurvey',
        'mande.view_postexitsurvey',
        'mande.view_academic',
        'mande.view_studentevaluation',
        'mande.view_discipline',
        'mande.view_health',
        'mande.view_classroomenrollment',
        'mande.view_attendance'
    },
    'attendance':{
        'mande.add_attendance',
        'mande.view_classroom',
        'mande.view_classroomenrollment',
        'mande.view_attendance',
        'mande.view_attendancedayoffering',
        'mande.view_attendancelog'
    },
    'attendance_calendar':{
        'mande.view_classroom',
        'mande.add_attendancedayoffering',
        'mande.change_attendancedayoffering'
    },
    'take_attendance':{
        'mande.add_attendance',
        'mande.view_classroom',
        'mande.view_classroomenrollment',
        'mande.view_attendance',
        'mande.view_attendancedayoffering',
        'mande.view_attendancelog'
    },
    'daily_attendance_report':{
        'mande.view_classroom',
        'mande.view_attendancedayoffering',
        'mande.view_attendance'
    },
    'daily_absence_report':{
        'mande.view_classroom',
        'mande.view_attendancedayoffering',
        'mande.view_attendance'
    },
    'data_audit':{
        'mande.view_exitsurvey',
        'mande.view_intakesurvey',
        'mande.view_intakeinternal',
        'mande.view_intakeupdate',
        'mande.view_academic',
        'mande.view_intakeupdate',
        'mande.view_attendance',
        'mande.view_classroomenrollment'
    },
    'class_list':{
        'mande.view_classroom',
        'mande.view_classroomteacher'
    },
    'exit_surveys_list':{
        'mande.view_exitsurvey',
        'mande.view_postexitsurvey'
    },
    'student_lag_report':{
        'mande.view_exitsurvey',
        'mande.view_intakesurvey',
        'mande.view_intakeinternal',
        'mande.view_intakeupdate'
    },
    'student_evaluation_report':{
        'mande.view_studentevaluation',
        'mande.view_classroom'
    },
    'student_medical_report':{
        'mande.view_exitsurvey',
        'mande.view_intakesurvey',
        'mande.view_intakeinternal',
        'mande.view_intakeupdate',
        'mande.view_health'
    },
    'student_dental_report':{
        'mande.view_exitsurvey',
        'mande.view_intakesurvey',
        'mande.view_intakeinternal',
        'mande.view_intakeupdate',
        'mande.view_health'
    },
    'mande_summary_report':{
        'mande.view_school',
        'mande.view_exitsurvey',
        'mande.view_intakesurvey',
        'mande.view_intakeupdate',
        'mande.view_classroomenrollment',
        'mande.view_classroom'
    },
    'student_promoted_report':{
        'mande.view_academic',
        'mande.view_intakesurvey',
        'mande.view_school'
    },
    'students_promoted_times_report':{
        'mande.view_school',
        'mande.view_intakesurvey',
        'mande.view_exitsurvey',
        'mande.view_academic'
    },
    'students_not_enrolled_in_public_school_report':{
        'mande.view_intakesurvey',
        'mande.view_exitsurvey'
    },
    'students_intergrated_in_public_school':{
        'mande.view_intakesurvey',
        'mande.view_intakeupdate'
    },
    'students_lag_summary':{
        'mande.view_intakesurvey',
        'mande.view_intakeinternal',
        'mande.view_exitsurvey',
        'mande.view_school'
    },
    'anomolous_data':{},
    'intake_survey':{
        'mande.add_intakesurvey',
        'mande.add_intakeinternal'
    },
    'intake_update':{
        'mande.add_intakeupdate'
    },
    'intake_internal':{
        'mande.add_intakeinternal'
    },
    'exit_survey':{
        'mande.add_exitsurvey'
    },
    'post_exit_survey':{
        'mande.add_postexitsurvey'
    },
    'spiritualactivities_survey':{
        'mande.add_spiritualactivitiessurvey'
    },
    'health_form':{
        'mande.add_health'
    },
    'discipline_form':{
        'mande.add_discipline'
    },
    'teacher_form':{
        'mande.add_teacher',
        'mande.change_teacher'
    },
    'classroom_form':{
        'mande.add_classroom',
        'mande.change_classroom'
    },
    'classroomteacher_form':{
        'mande.add_classroomteacher',
        'mande.change_classroomteacher'
    },
    'classroomenrollment_form':{
        'mande.view_classroom',
        'mande.view_school',
        'mande.add_classroomenrollment',
        'mande.change_classroomenrollment'
    },
    'academic_select':{
        'mande.add_academic'
    },
    'studentevaluation_select':{
        'mande.add_studentevaluation'
    }

}
